name: Deploy to GCP Nodes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GCLOUD_SSH_KEY }}

      - name: Deploy to HA Node 1
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCLOUD_USER }}@${{ secrets.GCLOUD_HOST_NODE1 }} "
            cd /var/www/my-project-web/app && \
            sudo docker build -t gscdockers/nfs-web:latest . && \
            sudo docker rm -f nfs-web || true && \
            sudo docker run -d -p 8080:8080 \
              -v /var/www/my-project-web/uploads:/app/uploads \
              -v ~/nfs-logger-key.json:/app/key.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/key.json \
              --name nfs-web gscdockers/nfs-web:latest

            cd /var/www/my-project && \
            sudo docker build -t gscdockers/my-project:latest . && \
            sudo docker rm -f my-project || true && \
            sudo docker run -d -p 3000:3000 --name my-project gscdockers/my-project:latest
          "

      - name: Deploy to HA Node 2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCLOUD_USER }}@${{ secrets.GCLOUD_HOST_NODE2 }} "
            cd /var/www/my-project-web/app && \
            sudo docker build -t gscdockers/nfs-web:latest . && \
            sudo docker rm -f nfs-web || true && \
            sudo docker run -d -p 8080:8080 \
              -v /var/www/my-project-web/uploads:/app/uploads \
              -v ~/nfs-logger-key.json:/app/key.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/key.json \
              --name nfs-web gscdockers/nfs-web:latest

            cd /var/www/my-project && \
            sudo docker build -t gscdockers/my-project:latest . && \
            sudo docker rm -f my-project || true && \
            sudo docker run -d -p 3000:3000 --name my-project gscdockers/my-project:latest
          "
