name: Build and Deploy Next.js via HTTPS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code via HTTPS
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Build Docker Image
        run: |
          cd /github/workspace
          docker build -t gscdockers/my-project:1.0 .

      - name: Push Docker Image to GCP Registry
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | gcloud auth activate-service-account --key-file=-
          gcloud auth configure-docker
          docker tag gscdockers/my-project:1.0 gcr.io/YOUR_PROJECT_ID/my-project:1.0
          docker push gcr.io/YOUR_PROJECT_ID/my-project:1.0

      - name: Deploy to Node 1 (GCP VM)
        run: |
          gcloud compute ssh gustavo@ha-node-1 --command "
          docker pull gcr.io/YOUR_PROJECT_ID/my-project:1.0 &&
          docker rm -f my-project || true &&
          docker run -d -p 3000:3000 --name my-project gcr.io/YOUR_PROJECT_ID/my-project:1.0
          "

      - name: Deploy to Node 2 (GCP VM)
        run: |
          gcloud compute ssh gustavo@ha-node-2 --command "
          docker pull gcr.io/YOUR_PROJECT_ID/my-project:1.0 &&
          docker rm -f my-project || true &&
          docker run -d -p 3000:3000 --name my-project gcr.io/YOUR_PROJECT_ID/my-project:1.0
          "
